#!/bin/sh

run() {
	input=($(ls *.md | sed -e 's/\.md$//' | fzf --preview='less {}.md' --preview-window=up --bind space:jump,jump:accept,enter:accept-or-print-query | head -n 1))
	file=${input[N-0]}
	#op=${input[N-1]}
	if [[ $file != 'q' ]] ; then
		read -p "(A)ppend, (I)ncrement/new, (E)dit, (D)elete, (Q)uit? " op
		new="$(./numbering ${file/.md/} $op)"

		case $op in

			i | a)
				echo "# $new" > $new.md
				echo "--------------------------------------------------------------------------------" >> $new.md
				$EDITOR $new.md
				./zettelkasten
				;;

			e)
				$EDITOR $new.md
				./zettelkasten
				;;

			d)
				rm $new.md
				./zettelkasten
				;;

			q | *)
				;;
		esac

	fi
}

run
