#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	l="ls -l" \
	la="ls -la" \
	ll="ls -la" \
	cal="cal -m" \
	d="date --iso-8601=seconds" \
	ed="ed --prompt='> '" \
	lynx="lynx -vikeys" \
	chrome="chromium" \
	browser="chromium" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	gd="git diff HEAD" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	tw="timew" \
	t="task" \
	rmf='rm "$(fzf)"'\
	vimfzf='vim "$(fzf)"'\
	mpm="mpv --no-video"\
	lf=". ~/.local/bin/lfcd"\

# Set personal aliases
alias \
	rdp='(){ xfreerdp /w:1920 /h:1000 /v:$1 ;}' \
	webc='(){ v4l2-ctl -d /dev/video0 -c exposure_absolute=$1; }' \
	rm='rm -i' \
	sloc="find -name '*.php' | xargs wc -l" \
	weather='curl wttr.in/\?0pQ' \
	ts="ts '[%Y-%m-%d %H:%M:%S]'" \
	vim_eisenhower="vim 4 -c 'split 2' -c 'vsplit 1' -c 'wincmd j' -c 'vsplit 3' -c 'wincmd k'" \
	figlet="figlet -f slant" \
	fortuneob="fortune oblique-strategies" \
	pacman_autoremove="pacman -Rcs $(pacman -Qdtq)" \
	'nerd-dictation'="${XDG_CONFIG_HOME}/nerd-dictation/nerd-dictation" \

# work
alias \
	dc_start='docker-compose up -d --remove-orphans --force-recreate' \
	dc_stop='docker-compose stop' \
	dc_stop_all='docker stop $(docker container ls -q)' \
	dc_remove='docker-compose down' \
	dc_test='docker-compose exec fpm vendor/bin/phpspec run -vv' \
	dc_bash='docker-compose exec fpm bash' \
	dc_update='docker-compose pull && docker-compose up -d --remove-orphans' \
	yarn_watch='docker-compose run -u node --rm -e YARN_REGISTRY -e PUPPETEER_SKIP_CHROMIUM_DOWNLOAD node yarn run webpack-dev --watch' \
	akeneo_queue='bin/docker/console messenger:consume ui_job import_export_job data_maintenance_job --env=prod' \
	akeneo_reset_indexes='bin/docker/console akeneo:elasticsearch:reset-indexes && bin/docker/console pim:product:index --all && bin/docker/console pim:product-model:index --all' \
	'bin/console'='bin/docker/console'

# enable failsafes
#alias \
#	newsboat='failsafe newsboat' \
#	neomutt='failsafe neomutt' \
#	firefox_p='failsafe firefox_p' \
#	firefox_y='failsafe firefox_y' \
