#!/bin/sh

redshift -O 5500k &			# Remove blue light
clipmenud &					# Enable clipboard history
#xcompmgr &					# Enable opacity
dwmtime &
dunst &						# Notifications
tester &

fixscreen &

v4l2-ctl -d /dev/video0 -c saturation=85 &	# fix webcam
v4l2-ctl -d /dev/video0 -c brightness=170 &
v4l2-ctl -d /dev/video0 -c contrast=85 &

ssh-agent dwm				# Start WM
