#!/bin/sh

setxkbmap -layout dvorak	# Enable the best keyboard layout :P
redshift -O 4000K &			# Remove blue light
numlockx &					# Enable numlock
clipmenud &					# Enable clipboard history
xcompmgr &					# Enable opacity
dwmblocks &					# Dwm title bar
dunst &						# Notifications
xset r rate 200 60 &		# Speed up xrate
unclutter &					# Hide cursor when not in use

feh --no-fehbg --bg-fill \
	"$XDG_DATA_HOME"/wallpaper.png &		# Set wallpaper

# setsid mousetweaks --dwell --dwell-time=1.2 \
# 	--threshold=10 -t 15 &					# mouse tweaks

v4l2-ctl -d /dev/video0 -c saturation=75 &	# fix webcam

mpv --no-audio-display --volume=50 \
	"$XDG_DATA_HOME"/win_XP_Startup.mp3 &	# start-up sound

transmission-qt &

ssh-agent dwm				# Start WM
