#!/bin/sh

redshift -O 5500k &			# Remove blue light
clipmenud &					# Enable clipboard history
xcompmgr &					# Enable opacity
numlockx &					# Set numlock
dunst &						# Notifications
dwmtime &					# Put time in head
tester &

fixscreen &					# Run several tweaks

v4l2-ctl -d /dev/video0 -c saturation=73 &	# fix webcam
v4l2-ctl -d /dev/video0 -c brightness=160 &
v4l2-ctl -d /dev/video0 -c contrast=55 &

ssh-agent dwm				# Start WM
